### ISSUE TITLE
Is this project dying?

### ISSUE THREAD

**Issue by kaspermarstal** [xtk/X#177]
Dear Project Developers,

XTK is an awesome tool kit that has clearly generated a lot of interest as is apparent from the many open issues. Kudos for developing this fantastic piece of software. 

Currently, there are a couple of open pull requests and people are even offering to implement JPEG2000 support but they are all met with a wall of silence. In addition, the last closed issues date back to November 2014 even though many new have been opened between then and now. I understand that things happen in real life and people move on. Maybe there is no more funding for the project. Maybe your research interest is elsewhere. But you should be aware that there are many happy users of this software that would be really sad to see XTK continue down this path.

Can you please be straightforward and say if you intend to maintain this project or not? If not, I am sure it is possible to find people willing manage the pull requests on this repo and take it off your hands. That is the beauty of open source.

**Comment by mel15** [comment]
I am also interested in what you are talking about because I am using XTK for doing my Bachelor Final Project so I think it's quite interesting to think about the future of XTK.

**Comment by NicolasRannou** [comment]
Thanks for bringing up this issue, this is an interesting and important discussion.

We indeed had very limited time and ressources to work on this project lately and are thinking about which is the best next step for this project.

The currently implementation of the library is reaching some limitations in terms of flexibility/accuracy and fixing everything will require a fair amount of work.

The option which seems the most reasonable to me is to evolve toward a solution using ThreeJS to power all the visualization. We would then be able to focus more on the medical imaging part without having to deal with all the WebGL implementation details. (http://threejs.org/)

Does it make sense to you? I've been doing some testings and it seems very promising.

Should I open a new ticket to know which features of XTK you definitely want to see in the new version and which new features you would like to see? We want to keep the code/migration as easy as possible but support all the file formats, single channel, multi-channel, time series, etc, in a better way. Same thing for VTK/STL models, etc. Also fix all the orientation issues and make sure all the implementation/calculations are correct with more in depth testings. Moreover, we will integrate new items such as widgets (http://www.vtk.org/Wiki/VTK_Widget_Examples).

**Comment by kaspermarstal** [comment]
Thank you for your kind reply. Yes, porting core visualisation methods to three.js and moving WebGL-related maintenance upstream is a fantastic plan. Reusing as much as possible from the existing code base and focus on quality re-implementations of core methods is definitely the right approach IMO. 

Please, do go ahead and create an issue, I am very happy to provide suggestions for features and I am sure a lot of other people are as well. I am particularly excited about better multi-channel, times series and widget support.

I believe I speak on behalf many others saying I am excited about your ideas for XTK.

**Comment by nrhorner** [comment]
I'm really happy to hear that this project will be carried on into the future. We will be using XTK to get mouse embryos displayed on the [International Mouse Phenotyping Consortium](http://www.mousephenotype.org/) web portal. 

Thanks for creating a great piece of software.

**Comment by rudolphpienaar** [comment]
Just to echo Nico's sentiments, the project is definitely NOT dying :-) 
We have been focusing internally a lot on apps built off xtk, which 
meant less resources for xtk itself. As Nico also said, we are also 
coming up against some of design limits and trying best to think around 
"not having to re-invent the wheel" but also maintain an agile and 
simple-to-use library.

We are currently strategizing on the best ways forward and we'd be more 
than happy to discuss ways of including the community's views (and of 
course the community's help!).

Best
-=R

**Comment by kaspermarstal** [comment]
Thank you for your insights Rudolph and Nico, this is great news. I think many members of the community would interested in helping out. Looking forward to hearing more about your plans.
